### ISSUE TITLE
Cant launch it

### ISSUE THREAD

**Issue by mrcsdl** [GoekhanDev/Rust-Drops-Grabber#2]
Hey, i tryed to launch it on my win 10 pc. when i start the py than the shell pops up for like 1 sec and closing instantly. When i try to run it in python idle this error apperas. i tryed this with chrome and firefox

Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\Users\Marc\Desktop\Rust-Drops-Grabber-main - Kopie\RustGrabber.py
Traceback (most recent call last):
  File "C:\Users\Marc\Desktop\Rust-Drops-Grabber-main - Kopie\RustGrabber.py", line 214, in <module>
    Twitch()
  File "C:\Users\Marc\Desktop\Rust-Drops-Grabber-main - Kopie\RustGrabber.py", line 32, in __init__
    self.Config = json.loads(open("config.json", "r+").read())
  File "C:\Users\Marc\Desktop\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Marc\Desktop\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Marc\Desktop\Python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 7 column 27 (char 178)
>>>

**Comment by GoekhanDev** [comment]
Seems to be a issue with your config file, be sure your config file looks like this

{
    "Config": {
        "OAuth": "Your Key",
        "Browser": "Firefox",
        "Headless": true,
        "ChromePath": "",
        "FirefoxPath": "C:/Users/<User>/AppData/Roaming/Mozilla/Firefox/Profiles/<Your Profile>"
    }
}
